### PR TITLE
DRAFT: Use csv for table data

### LINKED ISSUE #29: Update pages to use CSV linked tables/data
## What is the goal or purpose of this issue?
The purpose of this issue is to research and implement a process to link CSV data to the tables presented on each business area page. This way the downloadable CSV is always aligned with the information presented on each page. 

## This issue is resolved when...
- [ ] A database or centrally stored spreadsheet is the single source of Outcomes and Metrics information. Each outcomes table across the site pulls data from the database/spreadsheet. 
- [ ] Edits and additions to the outcomes can be added via the central database/spreadsheet

## Additional context
_Add any other context, screenshots, or links about the request here_

### PR DESCRIPTION
**Pull request by sknep**
This pull request resolves #29 

**This pull request changes...**
- Removes .XSLS files and replaces them with .CSV files in the _data folder
- Populates what were formerly markdown tables with the CSV data using an include/component

Note that some Excel files had two sheets, one for CMS-required and one for State-Specific. CSVs do not have multiple sheets, so these needs to be separate downloads. Today, only two MES Outcomes both have both.

**Steps to manually review and verify this change...**
1. Until we get a separate preview server, you can see the changes here https://sknep.github.io/CMCS-DSG-DSS-Certification/Outcomes%20and%20Metrics/Claims%20Processing/

### This pull request can be merged when…
- [x] The above pull request description is complete
- [x] The pull request author has tested the change successfully
- [x] The pull request author has assigned a CMS reviewer
- [x] The change has been reviewed and approved by CMS

### CODE REVIEW

**Comment by sknep** [comment]
Some notes to review with the team:
- CSVs do not have multiple sheets, so CMS-Required and State-Specific outcomes are in different downloadable files
- Download links still expect the files to exist on the `main` branch (so they will 404 until the PR is published). We were using this for downloading the Excel files directly, and I had hoped to not link to them in this manner because it's a little weird, however this is the only way to have downloadable CSVs that are also _data files in Jekyll.

**Comment by sknep** [comment]
Reviewed in today's meeting with Jamie, Mike, Paul, and Amy. No changes requested then, so time for final review with @NAretakis to make sure this meets the expectations.

**Review by mgwalker — APPROVED** [review]
mind blown

I did not know Jekyll could do this. This is amazing. I don't know if my approval counts for anything, but since I was tagged as a reviewer, here it is anyway!

**Review by nickarrow — APPROVED** [review]
This is so awesome. Well done!

**Comment by sknep** [comment]
Hey @NAretakis and @mgwalker, 

In looking at this again, the CSV files hosted on GitHub display the comma-separated text within the browser window frame (rather than, say, being automatically downloaded to the user's computer like an attachment when clicked): https://raw.githubusercontent.com/CMSgov/CMCS-DSG-DSS-Certification/main/_data/MES%20Outcomes%20-%20CMS-Required%20DSSDW.csv

As the CSVs are source content that GitHub hosts, and not outputted pages from Jekyll templates, this is 'intended behavior' but I'm not sure whether users will know how to turn the text in the browser window into an actual CSV that they could open in Excel. (Hint: press CTRL-S or Apple-S to open the "Save As" dialog and choose the folder.) Does this experience feel as unfinished to you as well?
1) visit page: https://cmsgov.github.io/CMCS-DSG-DSS-Certification/Outcomes%20and%20Metrics/Decision%20Support%20System%20&%20Data%20Warehouse/
2) Click the "Click here to download" links

If you agree that it doesn't feel great, I have some ideas but wanted to make sure that it was worth pursuing.

**Comment by sknep** [comment]
I started down this path today, open to thoughts and happy to chat about the approach if anyone is interested: https://github.com/CMSgov/CMCS-DSG-DSS-Certification-Staging/compare/make-csvs-downloadable?expand=1

**Comment by mgwalker** [comment]
Whoa, does this generate new CSVs from the source CSVs, so they can be hosted by Pages instead of having to point back to the repo? That is... a really clever hack around a very silly Jekyll limitation. I like it! 😄

**Comment by sknep** [comment]
yeah! when i added the `download` attribute to the anchor tag, it didn't work because that attribute only works on same-origin links. So I thought, "hey, those should really be hosted locally anyways"  :)

**Pull request merged**
