### PR TITLE
style tweaks; add header and footer

### LINKED ISSUE #17: MVP Visual style updates
## What is the goal or purpose of this issue?
Update the styles on the Github Pages site - work is currently happening in the read-the-docs branch. 

## This issue is resolved when...
- [x] Update .ds-h1 to `font-size: 48px` and `font-weight: 700` or `font-weight: bold`
- [x] Remove  `margin-left` from .ds-l-container
- [x] Update .content `padding-left: 2rem' 
- [x] Remove the CMS logo from the side nav
- [x] Add a header component with just the project name "MES Certification Repository" - no search bar or links. 
- [x] Can we add a slim footer w/ the CMS logo + Name and the copy "This site is maintained by the CMCS Data and Systems Group." 

## Additional context

I'm mainly trying to get a little closer to the cms design system

We may need to adjust the container or content margins after adding the header/footer

### PR DESCRIPTION
**Pull request by mgwalker**
This pull request resolves #17

**Description**

Does the things described in #17.

screenshot of the whole index page to show changes

**This pull request changes...**

- Adds a custom SCSS file and pulls it into the default layout
- Updates custom SCSS to override certain CMS DS properties
- Adds a header and footer

**Steps to manually review and verify this change...**

1. however people normally review changes, do that and then...
2. check that the `.ds-h1` elements have bigger font and heavier weight
3. check out that sweet header and footer

### This pull request can be merged when…

- [ ] The above pull request description is complete
- [ ] The pull request author has tested the change successfully
- [ ] The change has been reviewed and approved by CMS

### CODE REVIEW

**Comment by amyashida** [comment]
This looks great - any chance we could add a bit of margin to either the main container or the header + footer to give some breathing room on the top/bottom of the content?

**Comment by jadudm** [comment]
This looks great to me; according to the checklist, there's a CMS sign-off? Or, is that once things are "in production?" Essentially, I'm unsure if I should hit "merge" right now, or wait for Nick to chime in?

**Comment by amyashida** [comment]
> This looks great to me; according to the checklist, there's a CMS sign-off? Or, is that once things are "in production?" Essentially, I'm unsure if I should hit "merge" right now, or wait for Nick to chime in?

CMS signoff happens when things go to Main - right now we're just working in the branch :) We'll get Nick to do a review before things formally merge.

**Comment by mgwalker** [comment]
Updated with a `1rem` vertical margin on the main content area. Is this enough, or should it be 2rem? I went back and forth and they both looked nicer to me than no margin but I dunno.

screenshot showing the page with vertical margins added

**Comment by amyashida** [comment]
Let's do 2rem.

**Comment by mgwalker** [comment]
do'ed with two

**Comment by amyashida** [comment]
Looks good! Merging!

**Pull request merged**
